[lattice]
S = 3
N = 13
num_rings = 120
a = 4.05
dx = 5.13

[iter_pars.stoch_euler]
dt = 2.0
Tk_B = 0.004143
#Tk_B = 0.015143
damp_x = 0.1326
#damp_x = 0.326
damp_theta = 0.02487


[external.none]

[spring_consts]
K = 10.0
k_long = 1.5
k_lat = 1.5
k_in = 2.0
k_in_kin = 8.0
l0_long = 4.05
l0_lat = 4.86
l0_in = 4.05
l0_in_kin = 4.5