[lattice]
S = 3
N = 13
num_rings = 20
a = 4.05
dx = 5.13

[iter_pars.euler]
dt = 0.01
mass = 1.0
moment_inertia = 1.0
damp_x = 0.1
damp_theta = 0.02

[spring_consts]
K = 0.2
k_long = 2.0
# k_long = 1.5
k_lat = 1.5
k_in = 2.0
k_in_kin = 4.0
l0_long = 4.05
l0_lat = 4.86
l0_in = 4.05
# l0_in = 3.65
l0_in_kin = 4.5