[lattice]
S = 3
N = 13
num_rings = 5
a = 4.05
dx = 5.13

[iter_pars]
dt = 0.001
mass = 1.0
moment_inertia = 1.0
damp_x = 10.0
damp_theta = 10.0

[spring_consts]
K = 1.0
k_long = 1.5
k_lat = 1.5
k_in = 2.0
k_in_kin = 1.5
l0_long = 4.05
l0_lat = 4.86
l0_in = 3.65
l0_in_kin = 6.27