[lattice]
S = 3
N = 13
num_rings = 10
a = 4.05
dx = 5.13

[iter_pars.euler]
dt = 0.1
damp_x = 0.1326
damp_theta = 0.02487


[spring_consts]
K = 8.5
k_long = 3.5
k_lat = 14.0
k_in = 3.5
k_in_kin = 8.0
l0_long = 4.05
l0_lat = 5.21
l0_in = 4.05
l0_in_kin = 4.5


[external_force.youngs_modulus_pf]
F = 0.1